version: '3'
services:
  app:
    build: .
    ports:
    - 80:80
    - 443:443
    volumes:
    - .:/app
    - ./conf/php.ini:/opt/docker/etc/php/php.ini
    working_dir: /app/
    environment:
    - VIRTUAL_HOST=http://phpunit.local
    - LOG_STDERR=/marekerror.log



